services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./services/mqtt/config:/mosquitto/config:rw
      - ./services/mqtt/data:/mosquitto/data:rw
      - ./services/mqtt/log:/mosquitto/log:rw
    restart: unless-stopped

volumes:
  # volumes for mapping MQTT data,config and log
  config:
  data:
  log:

networks:
  default:
    name: dataminder-network