# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed here.
# See the documentation for the full list of configuration options.

## Start by adding some cameras
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: 'Dumpsite'
      host: 192.168.205.50
      port: 554
      path: '/stream0'
      username: 'admin'
      password: '123456'
      fps: 1
      substream:
        path: '/stream1'
        stream_format: rtsp
        port: 554
      mjpeg_streams:
        my_stream:
          width: 100
          height: 100
          draw_objects: true
          mirror: true
        objects:
          draw_objects: true
          draw_zones: true
          draw_motion: true
          draw_motion_mask: true
          draw_object_mask: true
      recorder:
        idle_timeout: 5
        lookback: 5
      frame_timeout: 10


    # camera_2:  # This value has to be unique across all cameras
    #   name: <camera friendly name>
    #   host: <ip address or hostname of camera>
    #   port: <port the camera listens on>
    #   path: <URL path to the stream>
    #   username: <if auth is enabled>
    #   password: <if auth is enabled>


## Then add an object detector
darknet:
  object_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

      # camera_2:  # Attach detector to the configured camera_2 above
      #   fps: 1
      #   labels:
      #     - label: person
      #       confidence: 0.75
      #       trigger_recorder: true


## You can also use motion detection
mog2:
  motion_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 1


## To tie everything together we need to configure one more component.
nvr:
  camera_1:  # Run NVR for camera_1
  # camera_2:  # Run NVR for camera_2

# Now you can restart Viseron and you should be good to go!
